name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out
        uses: actions/checkout@master

      - name: Make Short Test
        if: ${{ github.repository_owner != 'anz-bank' }}
        run: make short-test

      - name: Make Test
        if: ${{ github.repository_owner == 'anz-bank' }}
        run: make test
        env:
          TEST_PRIV_REPO_TOKEN: ${{ secrets.TEST_PRIV_REPO_TOKEN }}
